<a href="https://colab.research.google.com/github/PRAN20/Plant-Disease-Detection/blob/main/Accuracy-Inhancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Calculating Accuracy by Using Different Classification**

# **Importing Header Files**

In [ ]:
import pandas as ps
import numpy as np
import matplotlib.pyplot as plt
import os

# **Importing DataSet**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
#os.makedirs('dataset')

In [ ]:
!unzip "/content/drive/MyDrive/AlexNet-read.zip" -d "dataset"

Archive:  /content/drive/MyDrive/AlexNet-read.zip
 extracting: dataset/content/CSV-FILES/X_test.csv  
 extracting: dataset/content/CSV-FILES/X_train.csv  
 extracting: dataset/content/CSV-FILES/y_test.csv  
 extracting: dataset/content/CSV-FILES/y_train.csv  


In [ ]:
import pandas as pd
train_images=pd.read_csv("/content/dataset/content/CSV-FILES/X_train.csv",header=None)
x_train=train_images.iloc[:,:].values
x_train.shape

(8751, 1000)

In [ ]:
train_labels=pd.read_csv("/content/dataset/content/CSV-FILES/y_train.csv",header=None)
y_train=train_labels.iloc[:,:].values
y_train= y_train.flatten()
y_train.shape

(8751,)

In [ ]:
import pandas as pd
test_images=pd.read_csv("/content/dataset/content/CSV-FILES/X_test.csv",header=None)
x_test=test_images.iloc[:,:].values
x_test.shape

(10547, 1000)

In [ ]:
test_labels=pd.read_csv("/content/dataset/content/CSV-FILES/y_test.csv",header=None)
y_test=test_labels.iloc[:,:].values
y_test= y_test.flatten()
y_test.shape

(10547,)

# **Determing The Shape of all The Data**

In [ ]:
x_train.shape

(8751, 1000)

In [ ]:
y_train.shape

(8751,)

In [ ]:
x_test.shape

(10547, 1000)

In [ ]:
y_test.shape

(10547,)

# **Training The MLP Model**

In [ ]:
from sklearn.neural_network import MLPClassifier
classifier = MLPClassifier(max_iter = 500, activation = 'relu')
classifier.fit(x_train, y_train)

MLPClassifier(max_iter=500)

**Testing the Model**

In [ ]:
y_pred = classifier.predict(x_test)

In [ ]:
print(y_pred)
y_pred.shape

[36. 36. 36. ...  5.  2.  2.]


(10547,)

**Confusion Matrix**

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[  90,    0,    0, ...,    1,    0,    0],
       [   5,   70,    0, ...,    0,    0,    0],
       [   0,    0,   31, ...,    0,    0,    0],
       ...,
       [   0,    0,    4, ..., 1030,    0,    0],
       [   0,    0,    0, ...,    0,   73,    0],
       [   0,    0,    0, ...,    0,    0,  311]])

**Calculating the Accuracy of the Model**

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.79      0.82      0.80       110
         1.0       0.86      0.82      0.84        85
         2.0       0.60      0.52      0.55        60
         3.0       0.92      0.94      0.93       266
         4.0       0.96      0.97      0.97       229
         5.0       0.83      0.94      0.88       228
         6.0       0.96      0.89      0.93       202
         7.0       0.63      0.66      0.64       104
         8.0       0.93      0.99      0.96       233
         9.0       0.85      0.83      0.84       222
        10.0       0.99      0.97      0.98       221
        11.0       0.81      0.80      0.80       220
        12.0       0.87      0.85      0.86       232
        13.0       0.84      0.97      0.90       220
        14.0       0.97      0.90      0.93        79
        15.0       0.97      0.97      0.97      1166
        16.0       0.85      0.91      0.88       440
        17.0       0.88    

In [ ]:
from sklearn.metrics import accuracy_score
mlp = accuracy_score(y_test, y_pred)
mlp

0.8887835403432256

# **Naive-Bays Model**

In [ ]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(x_train, y_train)

GaussianNB()

In [ ]:
y_pred = clf.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
naive = accuracy_score(y_test, y_pred)
naive

[[ 59   5   1 ...   0   0   1]
 [  5  49   0 ...   0   0   0]
 [  1   0  34 ...   0   0   0]
 ...
 [  0   0   9 ... 118   0   0]
 [  3   0   0 ...   0  62   0]
 [  1   0   3 ...   0   0 238]]


0.5871811889636863

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.34      0.54      0.42       110
         1.0       0.34      0.58      0.43        85
         2.0       0.20      0.57      0.30        60
         3.0       0.45      0.68      0.55       266
         4.0       0.89      0.78      0.83       229
         5.0       0.65      0.39      0.49       228
         6.0       0.68      0.74      0.71       202
         7.0       0.39      0.50      0.44       104
         8.0       0.79      0.90      0.84       233
         9.0       0.70      0.56      0.62       222
        10.0       0.95      0.84      0.89       221
        11.0       0.26      0.26      0.26       220
        12.0       0.54      0.82      0.65       232
        13.0       0.31      0.85      0.46       220
        14.0       0.88      0.67      0.76        79
        15.0       0.66      0.68      0.67      1166
        16.0       0.72      0.38      0.49       440
        17.0       0.94    

# **Random Forest Classification**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf1 = RandomForestClassifier(n_estimators = 70, oob_score = True, n_jobs = -1,max_features = None, min_samples_leaf = 30)
clf1.fit(x_train, y_train)

RandomForestClassifier(max_features=None, min_samples_leaf=30, n_estimators=70,
                       n_jobs=-1, oob_score=True)

In [ ]:
y_pred = clf1.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
rand = accuracy_score(y_test, y_pred)
rand

[[  24    4    0 ...    4    0    3]
 [   2   42    0 ...    0    0    0]
 [   0    0    0 ...    3    0    0]
 ...
 [   0    0    0 ... 1016    0    0]
 [   0    0    0 ...    0   49    0]
 [   0    0    0 ...    0    0  262]]


0.7258936190385892

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.63      0.22      0.32       110
         1.0       0.59      0.49      0.54        85
         2.0       0.00      0.00      0.00        60
         3.0       0.57      0.74      0.64       266
         4.0       0.74      0.89      0.81       229
         5.0       0.67      0.47      0.55       228
         6.0       0.71      0.57      0.64       202
         7.0       0.68      0.16      0.26       104
         8.0       0.89      0.93      0.91       233
         9.0       0.71      0.64      0.68       222
        10.0       0.92      0.91      0.92       221
        11.0       0.54      0.42      0.48       220
        12.0       0.73      0.81      0.77       232
        13.0       0.78      0.66      0.71       220
        14.0       0.80      0.75      0.77        79
        15.0       0.83      0.94      0.88      1166
        16.0       0.79      0.74      0.76       440
        17.0       0.73    

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **K-NN**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier(n_neighbors = 15, metric = 'minkowski', p = 2)
kn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=15)

In [ ]:
y_pred = kn.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
knn = accuracy_score(y_test, y_pred)
knn

[[  43    3    0 ...    3    0    0]
 [   4   64    0 ...    0    0    0]
 [   1    0   16 ...    5    0    0]
 ...
 [   0    0    1 ... 1042    0    0]
 [   0    0    0 ...    0   72    0]
 [   0    0    0 ...    0    0  317]]


0.8178628994026738

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.64      0.39      0.49       110
         1.0       0.80      0.75      0.78        85
         2.0       0.67      0.27      0.38        60
         3.0       0.76      0.84      0.80       266
         4.0       0.82      0.97      0.89       229
         5.0       0.75      0.75      0.75       228
         6.0       0.86      0.83      0.84       202
         7.0       0.61      0.38      0.47       104
         8.0       0.96      0.96      0.96       233
         9.0       0.81      0.73      0.77       222
        10.0       0.96      0.97      0.96       221
        11.0       0.77      0.58      0.66       220
        12.0       0.78      0.89      0.83       232
        13.0       0.71      0.91      0.80       220
        14.0       0.83      0.86      0.84        79
        15.0       0.86      0.95      0.91      1166
        16.0       0.89      0.80      0.84       440
        17.0       0.72    

# **Decision Tree**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf2 = DecisionTreeClassifier(max_depth = 10, random_state = 101, max_features = None, min_samples_leaf = 15)
clf2.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=10, min_samples_leaf=15, random_state=101)

In [ ]:
y_pred = clf2.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
desc = accuracy_score(y_test, y_pred)
desc

[[  0   0   1 ...   2   0   0]
 [  0  14   0 ...   0   0   0]
 [  0   0   8 ...  10   0   0]
 ...
 [  0   0   0 ... 875   0   0]
 [  0   0   0 ...   0   0   1]
 [  0   0   4 ...   5   0 249]]


0.49028159666255805

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00       110
         1.0       0.36      0.16      0.23        85
         2.0       0.11      0.13      0.12        60
         3.0       0.53      0.52      0.53       266
         4.0       0.08      0.01      0.02       229
         5.0       0.56      0.26      0.35       228
         6.0       0.51      0.10      0.17       202
         7.0       0.00      0.00      0.00       104
         8.0       0.87      0.69      0.77       233
         9.0       0.53      0.24      0.33       222
        10.0       0.96      0.81      0.87       221
        11.0       0.47      0.26      0.34       220
        12.0       0.74      0.65      0.69       232
        13.0       0.24      0.08      0.12       220
        14.0       0.61      0.24      0.35        79
        15.0       0.86      0.71      0.78      1166
        16.0       0.63      0.45      0.52       440
        17.0       0.00    

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **Kernel SVM**

In [ ]:
from sklearn.svm import SVC
classifier1 = SVC(kernel = 'linear', C =  1,  random_state = 101)
classifier1.fit(x_train, y_train)

SVC(C=1, kernel='linear', random_state=101)

In [ ]:
y_pred = classifier1.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
svm = accuracy_score(y_test, y_pred)
svm

[[  94    0    1 ...    0    0    0]
 [   5   71    0 ...    0    0    0]
 [   0    0   41 ...    1    0    0]
 ...
 [   0    0    4 ... 1039    0    0]
 [   0    0    0 ...    0   74    0]
 [   0    0    0 ...    0    0  310]]


0.8921968332227174

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.80      0.85      0.83       110
         1.0       0.85      0.84      0.84        85
         2.0       0.61      0.68      0.65        60
         3.0       0.87      0.94      0.90       266
         4.0       0.97      0.96      0.96       229
         5.0       0.89      0.94      0.91       228
         6.0       0.92      0.91      0.92       202
         7.0       0.67      0.66      0.67       104
         8.0       0.96      0.98      0.97       233
         9.0       0.88      0.85      0.86       222
        10.0       0.98      0.99      0.98       221
        11.0       0.78      0.77      0.77       220
        12.0       0.87      0.87      0.87       232
        13.0       0.85      0.94      0.89       220
        14.0       1.00      0.94      0.97        79
        15.0       0.97      0.98      0.97      1166
        16.0       0.88      0.92      0.90       440
        17.0       0.91    

# **Linear SVC**

In [ ]:
from sklearn.svm import LinearSVC
class3 = LinearSVC(random_state=0, tol=1e-5)
class3.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,


LinearSVC(random_state=0, tol=1e-05)

In [ ]:
y_pred = class3.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
svc = accuracy_score(y_test, y_pred)
svc

[[  94    0    0 ...    0    0    0]
 [   3   68    0 ...    0    0    0]
 [   2    0   32 ...    5    0    0]
 ...
 [   0    0    1 ... 1052    0    0]
 [   0    0    0 ...    0   74    0]
 [   0    0    0 ...    0    0  316]]


0.8912486963117474

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.79      0.85      0.82       110
         1.0       0.80      0.80      0.80        85
         2.0       0.68      0.53      0.60        60
         3.0       0.89      0.90      0.89       266
         4.0       0.96      0.98      0.97       229
         5.0       0.91      0.94      0.93       228
         6.0       0.91      0.89      0.90       202
         7.0       0.69      0.65      0.67       104
         8.0       0.97      0.97      0.97       233
         9.0       0.88      0.86      0.87       222
        10.0       0.98      0.99      0.99       221
        11.0       0.80      0.80      0.80       220
        12.0       0.88      0.87      0.88       232
        13.0       0.90      0.94      0.92       220
        14.0       0.99      0.94      0.96        79
        15.0       0.97      0.98      0.97      1166
        16.0       0.87      0.91      0.89       440
        17.0       0.88    

# **Logistic Regression**

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier4 = LogisticRegression(random_state = 0)
classifier4.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(random_state=0)

In [ ]:
y_pred = classifier4.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
logis = accuracy_score(y_test, y_pred)
logis

[[  85    0    0 ...    0    0    0]
 [   3   68    0 ...    0    1    0]
 [   0    0   30 ...    4    0    0]
 ...
 [   0    0    1 ... 1045    0    0]
 [   0    0    0 ...    0   72    0]
 [   0    0    0 ...    0    0  306]]


0.8919123921494264

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.81      0.77      0.79       110
         1.0       0.86      0.80      0.83        85
         2.0       0.68      0.50      0.58        60
         3.0       0.87      0.93      0.90       266
         4.0       0.97      0.97      0.97       229
         5.0       0.93      0.93      0.93       228
         6.0       0.96      0.90      0.93       202
         7.0       0.75      0.63      0.69       104
         8.0       0.95      0.97      0.96       233
         9.0       0.84      0.85      0.84       222
        10.0       0.99      0.97      0.98       221
        11.0       0.84      0.83      0.83       220
        12.0       0.90      0.90      0.90       232
        13.0       0.87      0.95      0.91       220
        14.0       0.96      0.87      0.91        79
        15.0       0.97      0.98      0.98      1166
        16.0       0.90      0.93      0.91       440
        17.0       0.91    

# **Stochastic Gradient Descent**

In [ ]:
from sklearn.linear_model import SGDClassifier
sgd = SGDClassifier(loss = 'modified_huber', shuffle = True, random_state = 101)
sgd.fit(x_train, y_train)

SGDClassifier(loss='modified_huber', random_state=101)

In [ ]:
y_pred = sgd.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
stoc = accuracy_score(y_test, y_pred)
stoc

[[  92    0    1 ...    0    0    0]
 [   6   68    0 ...    0    0    0]
 [   0    0   29 ...    4    0    0]
 ...
 [   0    0    2 ... 1021    0    0]
 [   0    0    0 ...    0   73    0]
 [   0    0    1 ...    0    0  317]]


0.8731392813122215

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.70      0.84      0.76       110
         1.0       0.88      0.80      0.84        85
         2.0       0.71      0.48      0.57        60
         3.0       0.89      0.89      0.89       266
         4.0       0.99      0.97      0.98       229
         5.0       0.90      0.93      0.91       228
         6.0       0.96      0.79      0.86       202
         7.0       0.63      0.70      0.67       104
         8.0       0.94      0.97      0.95       233
         9.0       0.87      0.82      0.84       222
        10.0       0.99      0.98      0.99       221
        11.0       0.79      0.63      0.70       220
        12.0       0.76      0.92      0.83       232
        13.0       0.87      0.93      0.90       220
        14.0       0.98      0.82      0.90        79
        15.0       0.93      0.98      0.95      1166
        16.0       0.85      0.90      0.88       440
        17.0       0.84    

# **Final Results**

In [ ]:
print('Accuracy of MLP Model is {}'.format(mlp))
print('Accuracy of Naive-Bays Model is {}'.format(naive))
print('Accuracy of Random Forest Model is {}'.format(rand))
print('Accuracy of K-NN Model is {}'.format(knn))
print('Accuracy of Decision Tree Model is {}'.format(desc))
print('Accuracy of Kernel Svm Model is {}'.format(svm))
print('Accuracy of Linear SVC Model is {}'.format(svc))
print('Accuracy of Logistic Regression Model is {}'.format(logis))
print('Accuracy of Stochastic Gradient Descent Model is {}'.format(stoc))

Accuracy of MLP Model is 0.8887835403432256
Accuracy of Naive-Bays Model is 0.5871811889636863
Accuracy of Random Forest Model is 0.7258936190385892
Accuracy of K-NN Model is 0.8178628994026738
Accuracy of Decision Tree Model is 0.49028159666255805
Accuracy of Kernel Svm Model is 0.8921968332227174
Accuracy of Linear SVC Model is 0.8912486963117474
Accuracy of Logistic Regression Model is 0.8919123921494264
Accuracy of Stochastic Gradient Descent Model is 0.8731392813122215
